name: dart_countries_states
description: A Dart project that contains all the countries information about them. Support multiple languages.
version: 0.1.1
homepage: https://github.com/jffiorillo/dart-countries-states

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.4
  http: ^1.1.0
  logger: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.0.4
  test: ^1.16.8
